# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'

target 'SoapClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Gloss', '~> 2.0'
  pod 'Kingfisher'
  # Pods for SoapClient

  target 'SoapClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoapClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
